### ISSUE TITLE
Zsh completions aren't being generated

### ISSUE THREAD

**Issue by jason-riddle** [aelsabbahy/dargs#2]
Thanks for this awesome project! Looks like the zsh completions aren't being generated. Any ideas?

**Comment by aelsabbahy** [comment]
What happens when you run:
```
 dargs generate-completions -s zsh
```

Also, can you paste your `dargs.yml`

**Comment by jason-riddle** [comment]
```bash
# dargs generate-completions
FATAL File already exists: ~/.dargs/completions/bash/zzdargs_ssh
# dargs generate-completions -s zsh
 INFO Wrote ~/.dargs/completions/zsh/zzdargs_ssh
```

`dargs.yml`

```yml
imports:
  - ~/.dargs/config.d/*.yml

commands:
  - name: /usr/bin/ssh
    wrapper: ssh
    # Use fzf to fuzzy complete (must have fzf installed)
    #fzf-complete: true
    completers:
      - ec2_name
    transformers:
      - ec2_name # transforms ec2:instance_name -> instance-id (i-xxxxxxxx)
      - ec2_id # Transforms instance-id -> PrivateIpAddress
```
